### ISSUE TITLE
cannot unlock when use static value

### ISSUE THREAD

**Issue by pencilleaf** [go-redsync/redsync#103]
I want to fix the value so that a lock can be removed by a different client. According to the docs, I use WithGenValueFunc() to return a predefined value, and then use WithValue() to transfer ownership of the lock. 

I have a test case to verify if this is working with 3 mutex to lock/unlock the same key, but the behaviour is not what I expect..

```
func Test_RedsyncMutex(t *testing.T) {
	var err error

	redisCli := redis.NewClient(&redis.Options{
		Addr: addr,
	})

	rsync := redsync.New(goredis.NewPool(redisCli))
	token := "123"
	ctx := context.Background()

	mu := rsync.NewMutex(token, redsync.WithGenValueFunc(func() (string, error) {
		return token, nil
	}))

	err = mu.LockContext(ctx)
	if err != nil {
		t.Errorf("error locking 1")
	}

	received := make(chan int, 2)

	go func() {
		time.Sleep(30 * time.Millisecond)

		var isUnlocked bool

		mu2 := rsync.NewMutex(token, redsync.WithValue(token))

		isUnlocked, err = mu2.UnlockContext(ctx)

		if err != nil {
			t.Errorf("error unlocking 1")
		}

		if !isUnlocked {
			t.Errorf("expected unlock status: %v, got: %v", true, isUnlocked)
		}
		received <- 1
	}()

	go func() {
		mu3 := rsync.NewMutex(token,
			redsync.WithGenValueFunc(func() (string, error) {
				return token, nil
			}))

		err = mu3.LockContext(ctx)
		if err != nil {
			t.Errorf("error locking 2")
		}
		received <- 2
	}()

	res := []int{}
	for v := range received {
		res = append(res, v)

		if len(res) == 2 {
			close(received)
		}
	}

	if res[0] != 1 || res[1] != 2 {
		t.Errorf("lock mechanism not working")
	}
}
```

Expected this test case to pass but actual result I got was unlocked = false
```
=== RUN   Test_RedsyncMutex
    /Users/xxx/go/src/github.com/xxx/redsync_test.go:442: expected unlock status: true, got: false
--- FAIL: Test_RedsyncMutex (0.12s)
FAIL
```

**Comment by hjr265** [comment]
@pencilleaf Thank you for sharing this test. I took a very quick glance at it.

When you are defining mu3, the GenValueFunc you are giving it is producing the same value as mu and mu2. This will produce somewhat undefined behavior.

You can fix this test just by changing the GenValueFunc to return something other than token:

```
		mu3 := rsync.NewMutex(token,
			redsync.WithGenValueFunc(func() (string, error) {
				return "some other value", nil
			}))
```

Once mu has the lock with the value "123", attempting to acquire the same lock with the same value will cause the lock to be released. This is really just how the underlying redlock algorithm works. Mutex tries to acquire lock, if it fails, it cleans up. Since the value is the same, the original lock gets cleaned up. 

Let me know if you continue to face any issue after making this change.

**Comment by pencilleaf** [comment]
My idea was to make this work across instances, so that any instance can unlock the lock set by another. But this doesn't seem to be the goal of redlock algorithm.. 

After making your suggested change, it works perfectly fine. Thank you for your explanation!

**Comment by hjr265** [comment]
@pencilleaf Something you can try to do is:

- Always acquire lock with a new unique value.
- Transfer lock ownership by sharing that unique value.

In your test above, you can just give `mu3` a new value.

As long as you acquire lock with a new value every time, you should be good. Only to transfer ownership and release lock, reuse the current old value.
