### ISSUE TITLE
lock already taken, locked nodes: [0]

### ISSUE THREAD

**Issue by sunshine12319** [go-redsync/redsync#122]
import (
	"fmt"
	"github.com/go-redsync/redsync/v4"
	"github.com/go-redsync/redsync/v4/redis/goredis/v9"
	goredislib "github.com/redis/go-redis/v9"
	"sync"
	"time"
)
func main() {
	client := goredislib.NewClient(&goredislib.Options{
		Addr: "localhost:6379",
	})
	pool := goredis.NewPool(client) //or, pool :=redigo.NewPool

	rs := redsync.New(pool)
	//var num int
	var wg sync.WaitGroup
	wg.Add(20)
	for i := 0; i < 20; i++ {
		go func(i int) {
			defer wg.Done()
			mutex := rs.NewMutex("goods")

			if err := mutex.Lock(); err != nil {
				fmt.Println(err)
				return
			}
			fmt.Println("测试", i)
			time.Sleep(time.Second * 2)
			if ok, err := mutex.Unlock(); !ok || err != nil {
				fmt.Println(err)
				return
			}
		}(i)
	}
	wg.Wait()
}
//output:
/*
测试 3
测试 0
lock already taken, locked nodes: [0]
测试 6
lock already taken, locked nodes: [0]
lock already taken, locked nodes: [0]
lock already taken, locked nodes: [0]
lock already taken, locked nodes: [0]
lock already taken, locked nodes: [0]
lock already taken, locked nodes: [0]
lock already taken, locked nodes: [0]
lock already taken, locked nodes: [0]
lock already taken, locked nodes: [0]
lock already taken, locked nodes: [0]
lock already taken, locked nodes: [0]
lock already taken, locked nodes: [0]
lock already taken, locked nodes: [0]
lock already taken, locked nodes: [0]
lock already taken, locked nodes: [0]
lock already taken, locked nodes: [0]
*/
为什么这个分布式锁会死锁，不应该等待释放锁吗

**Comment by VermaShivansh** [comment]
facing same issue

**Comment by dvdalilue** [comment]
Hello @sunshine12319, I was passing by this repo and saw this issue. The error you are facing is expected because the `mutex.Lock()` operation exhausts all attempts to get a lock. When you create a `Mutex`, you have several options to adjust its behaviour to your needs. By default, it has an expiration time of 8 seconds, 32 retries, some delay mechanism between attempts to introduce some randomness, among other things.

So what is happening with your code? 20 goroutines are created with their own mutex, and each of them try to get a lock. After having a lock, they sleep for 2 seconds and then unlock. You see that 3 of them are successful, where the other 17 failed. This is beacuse their mutex instance were not able to get the lock with the default settings. Each gorountine adds 2 seconds of waiting time to the next one, and the mutex just stops trying at some point.

You could add a fixed delay time:
```
mutex := rs.NewMutex("goods", redsync.WithRetryDelay(2*time.Second))
```
Or could add a fixed number or retries:
```
mutex := rs.NewMutex("goods", redsync.WithTries(100))
```
Probably you want to combine both:
```
mutex := rs.NewMutex("goods",  redsync.WithRetryDelay(2*time.Second), redsync.WithTries(100))
```

These values are just to give an example, the settings must be based on your needs.
