### ISSUE TITLE
how do u use this thing

### ISSUE THREAD

**Issue by domino14** [go-redsync/redsync#5]

**Comment by MaerF0x0** [comment]
OTOH. probably doesnt even compile.

```go
func del_key(key string) bool, error
	redisUrl := "redis://localhost:6379"
        p := &redis.Pool{ 
        	Dial: func() (redis.Conn, error) {
			c, err := redis.DialURL(redisUrl)		
			return c, err
		},
	}
   rs := redsync.New([]Pool{p})

   m := rs.NewMutex("GLOBAL")

  var err error

  
  if err := m.Lock() ; err != nil {
    fmt.Println("Failed", err)
  } else  {
    fmt.Println("Acquired")
   defer m.Unlock()
  }

  c := p.Get()
  defer c.Close()
  return c.Do("DEL", "something")
} 
```

**Comment by hjr265** [comment]
@MaerF0x0 I suppose you mean the snippet above doesn't compile. I tried it out locally with Redsync and Redigo. Had to made two tiny changes to get it through the compiler:

``` go
func del_key(key string) (interface{}, error) {
	redisUrl := "redis://localhost:6379"
	p := &redis.Pool{
		Dial: func() (redis.Conn, error) {
			c, err := redis.DialURL(redisUrl)
			return c, err
		},
	}
	rs := redsync.New([]redsync.Pool{p})

	m := rs.NewMutex("GLOBAL")

	if err := m.Lock(); err != nil {
		fmt.Println("Failed", err)
	} else {
		fmt.Println("Acquired")
		defer m.Unlock()
	}

	c := p.Get()
	defer c.Close()
	return c.Do("DEL", "something")
}
```

**Comment by SebastiaanKlippert** [comment]
Thanks for the sample. I am correct in assuming I can create one global Redsync var using redsync.New([]Pool{p}) or do I need a new one for each mutex?

I have done some tests using the global var using the race detector and it seems to run OK, but I am not sure because the pool is shared in NewMutex.

Also, if we have multiple Go instances (load balanced environment), will a single mutex be sufficient? I looks like you are using a local mutex inside the redsync mutex so on one instance it will work, but what if two or more Go instances will lock the same value? https://redis.io/topics/distlock talks about multiple Redis instances, but I am unsure how that translates to multiple Go instances.

Sorry if this is a novice question, but I think the docs could have some more info about the use cases and I am trying to "Make sure I understand how it works before using it in production environments." 😃 
Thanks.

**Comment by hjr265** [comment]
Hi @SebastiaanKlippert, thanks for trying it out. Glad to know it is working for you OK!
