### ISSUE TITLE
What if lock expires before unlock?

### ISSUE THREAD

**Issue by JodeZer** [go-redsync/redsync#6]
l'm a little confused about this lock though l've learn something about redlock.
Suppose l have a 8 seconds lock and the worker goroutine need 10 seconds to be done,(not always, sometimes).Another process in the cluster may get the lock cause it has been expired.
l dont think the `extend` func will work ,cause lock keeper can't always know how long it has already run.(Suppose a io-wait issue or a long GC pause or something like that.)
Please teach me the right way (or right place) to use.
ps: l'm planing to design a distributed lock to protect a large redis zset ,ensure only one process operates it at mean time.

**Comment by deckarep** [comment]
One solution could be to set a ridiculously large expiry ensuring that the lock never times out...but the caveat here is that you must, must, must take a considerable caution to ensure your application releases the lock after the work is finished.  This guarantee is not an easy task because you can also get into a state where your app crashes.

In that scenario swallowing the panic would still allow you an opportunity to release the lock.  This is why a timeout is a good thing.

**Comment by robstrong** [comment]
The worker goroutine should attempt to call `Extend()` before the 8 second deadline. If for some reason it gets delayed, the lock expires, and another worker gets the lock, then when the first goroutine attempts to call `Extend()` it will return false, indicating that the lock was lost and it should exit. This will allow the new worker to complete the job.

If you're really worried about this situation, I would just call `Extend()` more frequently (like every 4 seconds).
